

defaults:
  - _self_

seed: 42

paths:
  data_root: data/augmented
  outputs_root: outputs
  checkpoints: ${paths.outputs_root}/checkpoints

trainer:
  image_size: 256
  channels: 64
  channel_mults: [1, 2, 2, 4]
  num_res_blocks: 2
  attention_resolutions: [32]
  timesteps: 1000
  batch_size: 16
  lr: 2e-4
  max_steps: 100000
  log_interval: 100
  ckpt_interval: 1000
  gpus: 2
  mixed_precision: true
  grad_checkpoint: true

inference:
  num_images: 8
  steps: 50
  guidance_scale: 1.0
  out_dir: ${paths.outputs_root}/samples
  checkpoint: ${paths.checkpoints}/last.pt

segmentation:
  image_size: ${trainer.image_size}
  num_classes: 16
  channels: 32

vectorization:
  max_layers: 20
  max_anchors: 300
  curve_simplify_eps: 1.5
  bezier_segments: 8
  out_dir: ${paths.outputs_root}/vectors

ui:
  host: 127.0.0.1
  port: 5000